language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      cache:
        ccache:
        directories: '$HOME/.sonar/cache'
    - os: osx
      osx_image: xcode7.2
      compiler: clang

before_install:
      - ./.travis/install.sh
addons:
  sonarcloud:
    organization: "avrabe-github"
    token: $SONAR_TOKEN
script:
      - ./.travis/script.sh