sudo: required
dist: trusty
language:
  - cpp
compiler:
  - gcc
cache: ccache

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
      - sudo apt-get -qq update
      - sudo apt-get install -y curl cmake cmake-data build-essential libssl-dev gcc-6 g++-6 gfortran
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
      - sudo sh -c "(cd $TRAVIS_BUILD_DIR && git clone https://github.com/libuv/libuv.git && cd libuv && git checkout v1.12.0 && sh autogen.sh && ./configure && make -j 4 && make install && cd .. && rm -rf libuv)"
      - sudo sh -c "(cd $TRAVIS_BUILD_DIR && sh ./install-ubuntu.sh )"
addons:
  sonarcloud:
    organization: "avrabe-github"
    token: $SONAR_TOKEN
script:
  #- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  #- export CC=/usr/bin/gcc-6
  #- export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir -p build
  - cd build
  - cmake ..
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dproject.settings=$TRAVIS_BUILD_DIR/sonar-project.properties
cache:
  directories:
    - '$HOME/.sonar/cache'  
