language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      cache:
        ccache:
        directories: '$HOME/.sonar/cache'
      addons:
        sonarcloud:
          organization: "avrabe-github"
          token: $SONAR_TOKEN
    - os: osx
      osx_image: xcode7.3.1
      compiler: clang

before_install:
      - ./.travis/install.sh

script:
      - ./.travis/script.sh